create table CCCOFERTEWEB
(
	CCCOFERTEWEB INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(100) NOT NULL,
	FILENAME VARCHAR(MAX) NOT NULL,
	TRNDATE DATETIME NOT NULL DEFAULT GETDATE(),
	TRDR INT NOT NULL,
	PRJC INT,
	JSONSTR VARCHAR(MAX) NOT NULL
)

create table CCCAFLWEB
(
	CCCAFLWEB INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    CCCOFERTEWEB INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
	FILENAME VARCHAR(MAX) NOT NULL,
	TRNDATE DATETIME NOT NULL DEFAULT GETDATE(),
	TRDR INT NOT NULL,
	PRJC INT,
	JSONSTR VARCHAR(MAX) NOT NULL
)

--CCCLINIIWEB
create table CCCLINIIWEB
(
    CCCLINIIWEB INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    CCCOFERTEWEB INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    FILENAME VARCHAR(MAX) NOT NULL,
    TRNDATE DATETIME NOT NULL DEFAULT GETDATE(),
    TRDR INT NOT NULL,
    PRJC INT,
    JSONSTR VARCHAR(MAX) NOT NULL
)