create table CCCOFERTEWEB
(
	CCCOFERTEWEB INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(100) NOT NULL,
	FILENAME VARCHAR(MAX) NOT NULL,
	TRNDATE DATETIME NOT NULL DEFAULT GETDATE(),
	TRDR INT NOT NULL,
	PRJC INT NOT NULL,
	JSONSTR VARCHAR(MAX) NOT NULL
)

--create global table for all errors in the system
/*
SELECT ERROR_NUMBER() AS ErrorNumber,
    ERROR_SEVERITY() AS ErrorSeverity,
    ERROR_STATE() AS ErrorState,
    ERROR_PROCEDURE() AS ErrorProcedure,
    ERROR_LINE() AS ErrorLine,
    ERROR_MESSAGE() AS ErrorMessage;
*/
create table CCCWEBERRORS
(
	CCCWEBERRORS INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TRNDATE DATETIME NOT NULL DEFAULT GETDATE(),
	ERRORNUMBER INT NOT NULL,
	ERRORSEVERITY INT NOT NULL,
	ERRORSTATE INT NOT NULL,
	ERRORPROCEDURE VARCHAR(100),
	ERRORLINE INT NOT NULL,
	ERRORMESSAGE VARCHAR(MAX) NOT NULL
)
