IF NOT EXISTS (
	SELECT 1
	FROM sys.tables
	WHERE name = 'CCCOFERTEWEB'
) BEGIN CREATE TABLE CCCOFERTEWEB (
	CCCOFERTEWEB INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(100) NOT NULL,
	FILENAME VARCHAR(MAX) NOT NULL,
	TRNDATE DATETIME NOT NULL DEFAULT GETDATE(),
	TRDR INT NOT NULL,
	PRJC INT NOT NULL,
	JSONSTR VARCHAR(MAX) NOT NULL,
	JSONANTESTR VARCHAR(MAX),
	JSONINSTRETSTR VARCHAR(MAX),
	JSONRETETESTR VARCHAR(MAX),
	JSONTREESSTR VARCHAR(MAX),
	JSONESTIMPOOLSTR VARCHAR(MAX),
	JSONTREESTR VARCHAR(MAX)
)
END;

/*
 WBS, GRUPARE_ARTICOL_OFERTA, DENUMIRE_ARTICOL_OFERTA, SERIE_ARTICOL_OFERTA, TIP_ARTICOL_OFERTA, SUBTIP_ARTICOL_OFERTA, NIVEL_OFERTA_1, NIVEL_OFERTA_2, UM_ARTICOL_OFERTA, CANTITATE_ARTICOL_OFERTA, COST_UNITAR_MATERIAL_ARTICOL_OFERTA, COST_UNITAR_MANOPERA_ARTICOL_OFERTA, COST_UNITAR_UTILAJ_ARTICOL_OFERTA, COST_UNITAR_TRANSPORT_ARTICOL_OFERTA, NORMA_UNITARA_ORE_MANOPERA_ARTICOL_OFERTA, COST_UNITAR_ARTICOL_OFERTA, COST_TOTAL_MATERIAL_ARTICOL_OFERTA, COST_TOTAL_MANOPERA_ARTICOL_OFERTA, COST_TOTAL_UTILAJ_ARTICOL_OFERTA, COST_TOTAL_TRANSPORT_ARTICOL_OFERTA, COST_TOTAL_ARTICOL_OFERTA, TOTAL_ORE_MANOPERA_ARTICOL_OFERTA, PRET_UNITAR_MATERIAL_ARTICOL_OFERTA, PRET_UNITAR_MANOPERA_ARTICOL_OFERTA, PRET_UNITAR_UTILAJ_ARTICOL_OFERTA, PRET_UNITAR_TRANSPORT_ARTICOL_OFERTA, PRET_UNITAR_ARTICOL_ARTICOL_OFERTA, PRET_TOTAL_MATERIAL_ARTICOL_OFERTA, PRET_TOTAL_MANOPERA_ARTICOL_OFERTA, PRET_TOTAL_UTILAJ_ARTICOL_OFERTA, PRET_TOTAL_TRANSPORT_ARTICOL_OFERTA, PRET_TOTAL_ARTICOL_ARTICOL_OFERTA
 column names will be truncated to max 30 characters like the following:
 */
IF NOT EXISTS (
	SELECT 1
	FROM sys.tables
	WHERE name = 'CCCOFERTEWEBLINII'
) BEGIN CREATE TABLE CCCOFERTEWEBLINII (
	CCCOFERTEWEBLINII INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	CCCOFERTEWEB INT NOT NULL,
	WBS VARCHAR(100) NOT NULL,
	GRUPARE_ART_OF VARCHAR(100),
	DENUMIRE_ART_OF VARCHAR(350) NOT NULL,
	SERIE_ART_OF VARCHAR(100),
	TIP_ART_OF VARCHAR(100) NOT NULL,
	SUBTIP_ART_OF VARCHAR(100) NOT NULL,
	NIVEL_OF_1 VARCHAR(100),
	NIVEL_OF_2 VARCHAR(100),
	NIVEL_OF_3 VARCHAR(100),
	NIVEL_OF_4 VARCHAR(100),
	NIVEL_OF_5 VARCHAR(100),
	NIVEL_OF_6 VARCHAR(100),
	NIVEL_OF_7 VARCHAR(100),
	NIVEL_OF_8 VARCHAR(100),
	NIVEL_OF_9 VARCHAR(100),
	NIVEL_OF_10 VARCHAR(100),
	UM_ART_OF VARCHAR(10) NOT NULL,
	CANT_ART_OF FLOAT NOT NULL,
	COST_UNTR_MTRL_ART_OF FLOAT,
	COST_UNTR_MAN_ART_OF FLOAT,
	COST_UNTR_UTL_ART_OF FLOAT,
	COST_UNTR_TRNS_ART_OF FLOAT,
	NORMA_UNTR_ORE_MAN_ART_OF FLOAT,
	COST_UNTR_ART_OF FLOAT,
	COST_TOTAL_MTRL_ART_OF FLOAT,
	COST_TOTAL_MAN_ART_OF FLOAT,
	COST_TOTAL_UTL_ART_OF FLOAT,
	COST_TOTAL_TRNS_ART_OF FLOAT,
	COST_TOTAL_ART_OF FLOAT,
	TOTAL_ORE_MAN_ART_OF FLOAT,
	PRET_UNTR_MTRL_ART_OF FLOAT,
	PRET_UNTR_MAN_ART_OF FLOAT,
	PRET_UNTR_UTL_ART_OF FLOAT,
	PRET_UNTR_TRNS_ART_OF FLOAT,
	PRET_UNTR_ART_ART_OF FLOAT,
	PRET_TOTAL_MTRL_ART_OF FLOAT,
	PRET_TOTAL_MAN_ART_OF FLOAT,
	PRET_TOTAL_UTL_ART_OF FLOAT,
	PRET_TOTAL_TRNS_ART_OF FLOAT,
	PRET_TOTAL_ART_ART_OF FLOAT
)
END;

IF NOT EXISTS (
	SELECT 1
	FROM sys.tables
	WHERE name = 'CCCWEBERRORS'
) BEGIN CREATE TABLE CCCWEBERRORS (
	CCCWEBERRORS INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	TRNDATE DATETIME NOT NULL DEFAULT GETDATE(),
	ERRORNUMBER INT NOT NULL,
	ERRORSEVERITY INT NOT NULL,
	ERRORSTATE INT NOT NULL,
	ERRORPROCEDURE VARCHAR(100),
	ERRORLINE INT NOT NULL,
	ERRORMESSAGE VARCHAR(MAX) NOT NULL
)
END;

IF NOT EXISTS (
	SELECT 1
	FROM sys.tables
	WHERE name = 'CCCESTIMARIH'
) BEGIN CREATE TABLE CCCESTIMARIH (
	CCCESTIMARIH INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	CCCOFERTEWEB INT NOT NULL,
	ID INT NOT NULL,
	ACTIVE SMALLINT NOT NULL,
	STARTDATE DATETIME NOT NULL,
	ENDDATE DATETIME NOT NULL,
	CREATEDATE DATETIME NOT NULL,
	UPDATEDATE DATETIME,
	DSESTIMARIFLAT VARCHAR(MAX) NOT NULL
)
END;

IF NOT EXISTS (
	SELECT 1
	FROM sys.tables
	WHERE name = 'CCCESTIMARIL'
) BEGIN CREATE TABLE CCCESTIMARIL (
	CCCESTIMARIL INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	CCCESTIMARIH INT NOT NULL,
	STARTDATE DATETIME NOT NULL,
	ENDDATE DATETIME NOT NULL,
	WBS VARCHAR(100) NOT NULL,
	DENUMIRE VARCHAR(250) NOT NULL,
	CANTOFERTA FLOAT NOT NULL,
	CANTANTE FLOAT NOT NULL,
	CANTESTIM FLOAT NOT NULL,
	UM VARCHAR(10) NOT NULL,
	NIVEL_OFERTA_1 VARCHAR(100),
	NIVEL_OFERTA_2 VARCHAR(100),
	NIVEL_OFERTA_3 VARCHAR(100),
	NIVEL_OFERTA_4 VARCHAR(100),
	NIVEL_OFERTA_5 VARCHAR(100),
	NIVEL_OFERTA_6 VARCHAR(100),
	NIVEL_OFERTA_7 VARCHAR(100),
	NIVEL_OFERTA_8 VARCHAR(100),
	NIVEL_OFERTA_9 VARCHAR(100),
	NIVEL_OFERTA_10 VARCHAR(100),
	REFINSTANTA INT NOT NULL,
	REFRAMURA INT NOT NULL,
	REFACTIVITATE INT NOT NULL,
	REFESTIMARE INT NOT NULL,
	ROWSELECTED SMALLINT NOT NULL,
	TIPARTICOL VARCHAR(100) NOT NULL,
	SUBTIPARTICOL VARCHAR(100) NOT NULL,
	ISMAIN SMALLINT NOT NULL
);
END;

--select version
SELECT @@VERSION;
/*Microsoft SQL Server 2012 - 11.0.5058.0 (X64) 
 May 14 2014 18:34:29 
 Copyright (c) Microsoft Corporation
 Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 20348: ) (Hypervisor)
 */
create TABLE CCCUNIQNODES (
	CCCOFERTEWEB INT NOT NULL,
	CCCUNIQNODES INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(100) NOT NULL
);

CREATE TABLE CCCPATHS (
	CCCPATHS INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	CCCOFERTEWEB INT NOT NULL,
	PATH VARCHAR(MAX) NOT NULL,
	ISEXTENSIBLE SMALLINT NOT NULL DEFAULT 1
);

create table CCCRETETE (
	CCCOFERTEWEB INT NOT NULL,
	CCCRETETE INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(100) NOT NULL
);

CREATE TABLE CCCACTIVITRETETE (
	CCCOFERTEWEB INT NOT NULL,
	CCCRETETE INT NOT NULL,
	CCCACTIVITRETETE INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	CCCOFERTEWEBLINII INT NOT NULL,
	PONDEREDECONT FLOAT NOT NULL,
	PONDERENORMA FLOAT,
	ISMAIN SMALLINT NOT NULL DEFAULT 0,
	ISCUSTOM SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE CCCMATRETETE (
	CCCOFERTEWEB INT NOT NULL,
	CCCRETETE INT NOT NULL,
	ID INT NOT NULL,
	CCCMATRETETE INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	CCCACTIVITRETETE INT NOT NULL,
	CCCOFERTEWEBLINII INT NOT NULL,
	PONDEREDECONT FLOAT NOT NULL,
	PONDERENORMA FLOAT,
	ISCUSTOM SMALLINT NOT NULL DEFAULT 0
)

CREATE TABLE CCCTIPARTICOL (
	CCCTIPARTICOL INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(100) NOT NULL
)

CREATE TABLE CCCSUBTIPARTICOL (
	CCCSUBTIPARTICOL INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(100) NOT NULL
)

--'ARTICOL', 'SUBARTICOL', 'MATERIAL'
INSERT INTO CCCTIPARTICOL (NAME) VALUES ('ARTICOL'), ('SUBARTICOL'), ('MATERIAL')

/*
PRINCIPAL',
  'MATERIAL',
  'MANOPERA',
  'TRANSPORT',
  'ECHIPAMENT',
  'UTILAJ',
  'CUSTOM'*/

INSERT INTO CCCSUBTIPARTICOL (NAME) VALUES ('PRINCIPAL'), ('MATERIAL'), ('MANOPERA'), ('TRANSPORT'), ('ECHIPAMENT'), ('UTILAJ'), ('CUSTOM')